MariadbGalera:
  build:
  deployment_strategy: high_availability
  environment:
    - BALANCE=leastconn
    - 'EXCLUDE_PORTS=4567,4568,4444,9200'
    - 'HEALTH_CHECK=check port 9200 inter 5000 fastinter 2000 rise 2 fall 2'
    - OPTION=httpchk
    - TCP_PORTS=3306
    - 'wsrep_sst_auth=<SST_REPLICATION_SQL_USER>:<PASSWORD_FOR_SQL_USER>'
  expose:
    - '3306'
  restart: on-failure
  roles:
    - global
  sequential_deployment: true
  tags:
    - prod
  target_num_containers: 4
  volumes:
    - /var/lib/mysql
MariadbProxy:
  image: 'tutum/haproxy:latest'
  expose:
    - '80'
    - '443'
  links:
    - MariadbGalera
  ports:
    - '1936'
  restart: on-failure
  roles:
    - global
